<?php

namespace Database\Factories;

use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

class HotelFactory extends Factory
{
    public function definition(): array
    {
        $city = fake()->city();

        return [
            'user_id'        => User::factory(), // Auto-creates a user if not provided
            'name'           => fake()->company() . ' Hotel',
            'slug'           => null, // Auto-generated by model boot
            'description'    => fake()->paragraph(3),
            'address'        => fake()->streetAddress(),
            'city'           => $city,
            'state'          => fake()->state(),
            'country'        => 'USA',
            'zip_code'       => fake()->postcode(),
            'latitude'       => fake()->latitude(),
            'longitude'      => fake()->longitude(),
            'star_rating'    => fake()->numberBetween(1, 5),
            'check_in_time'  => '14:00',
            'check_out_time' => '11:00',
            'images'         => [
                'https://example.com/hotel1.jpg',
                'https://example.com/hotel2.jpg',
            ],
            'amenities'      => fake()->randomElements(
                ['wifi', 'pool', 'spa', 'gym', 'restaurant', 'bar', 'parking'],
                3
            ),
            'is_active'      => true,
        ];
    }

    /**
     * State: Inactive hotel
     */
    public function inactive(): static
    {
        return $this->state(fn() => ['is_active' => false]);
    }

    /**
     * State: 5-star hotel
     */
    public function luxury(): static
    {
        return $this->state(fn() => [
            'star_rating' => 5,
            'amenities'   => ['wifi', 'pool', 'spa', 'gym', 'restaurant', 'bar', 'valet_parking'],
        ]);
    }
}
